"use client";
import { Button } from "../ui/button";

export function DownloadSummaryButton({
  title,
  fileName,
  summaryText,
  createdAt,
}: {
  title: string;
  fileName: string;
  summaryText: string;
  createdAt: string;
}) {
  const handleDownload = () => {
    const summaryContent = `# ${title}
Generated Summary
Generated on: ${new Date(createdAt).toLocaleDateString()}

${summaryText}

Original File: ${fileName}
Generated by Brevio
`;
    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;

    // Sanitize filename: replace non-alphanumeric blocks with a single underscore
    const safeTitle = title.replace(/[^a-z0-9]+/gi, "_").toLowerCase();
    link.download = `Summary-${safeTitle}.txt`;

    // Required for Firefox visibility and to avoid removeChild errors
    document.body.appendChild(link);
    link.click();

    // Cleanup
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };
  return (
    <Button
      size="sm"
      className="h-8 px-3 bg-rose-100 text-rose-600 hover:text-rose-700 hover:bg-rose-50"
      onClick={handleDownload}
    >
      Download Summary
    </Button>
  );
}
